---
- name: Configure fonts - Interface Text
  dconf:
    key: "/org/gnome/desktop/interface/font-name"
    value: "'Ubuntu Light 11'"
    state: present

- name: Configure fonts - Document Text
  dconf:
    key: "/org/gnome/desktop/interface/document-font-name"
    value: "'Ubuntu Light 9'"
    state: present

- name: Configure fonts - Monospace Text
  dconf:
    key: "/org/gnome/desktop/interface/monospace-font-name"
    value: "'Roboto Mono Thin for Powerline Thin 9'"
    state: present

- name: Configure fonts - Window Title
  dconf:
    key: "/org/gnome/desktop/wm/preferences/titlebar-font"
    value: "'Ubuntu Light 11'"
    state: present

- name: Configure Scaling
  dconf:
    key: "/org/gnome/desktop/interface/text-scaling-factor"
    value: "0.9"
    state: present

- name: Favourite Apps Bar
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: ['org.gnome.Nautilus.desktop', 'chromium_chromium.desktop', 'rider_rider.desktop', 'code_code.desktop', 'alacritty_alacritty.desktop', 'postman_postman.desktop', 'gitkraken_gitkraken.desktop', 'intellij-idea-ultimate_intellij-idea-ultimate.desktop', 'storage-explorer_storage-explorer.desktop', 'authy_authy.desktop', 'slack_slack.desktop']
    state: present