---
- name: Gather the apt package facts
  package_facts:
    manager: auto
  no_log: "true"

- name: Check whether a package called flameshot is installed
  debug:
    msg: "{{ ansible_facts.packages['flameshot'] | length }} versions of flameshot are installed!"
  when: "'flameshot' in ansible_facts.packages"

# - name: Print the package facts
#   debug:
#     var: ansible_facts.packages['flameshot']
#   when: "'flameshot' in ansible_facts.packages"

- name: Set the version, assuming first package
  set_fact:
    flameshot_installed_version: "{{ ansible_facts.packages['flameshot'][0]['version'] }}"
  when: "'flameshot' in ansible_facts.packages"

- name: Print the version, assuming first package
  debug:
    var: flameshot_installed_version
  when: "'flameshot' in ansible_facts.packages"

- name: Install flameshot deb from github
  become: true
  apt:
    deb: >-
      {{ flameshot_url }}/v{{ flameshot_version }}/flameshot_{{ flameshot_version }}_bionic_x86_64.deb
  when: "'flameshot' not in ansible_facts.packages or flameshot_version not in flameshot_installed_version"

- name: Create autostart directory if it doesn't exist
  file:
    path: "~{{ user.username }}/.config/autostart/"
    state: directory
    mode: "0755"
  with_items: '{{ users }}'
  loop_control:
    loop_var: user
    label: '{{ user.username }}'

- name: Make flameshot startup automatically
  copy:
    src: "{{ role_path }}/files/Flameshot.desktop"
    dest: "~{{ user.username }}/.config/autostart/Flameshot.desktop"
    owner: "{{ user.username }}"
    group: "{{ user.username }}"
    mode: "0644"
  ignore_errors: yes # for GitHub Actions group being docker (fix wanted!)
  with_items: '{{ users }}'
  loop_control:
    loop_var: user
    label: '{{ user.username }}'
